[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
yog-cli = { path = "crates/yog-cli" }
yog-core = { path = "crates/yog-core" }
yog-gpui = { path = "crates/yog-gpui" }
yog-runtime = { path = "crates/yog-runtime" }
yog-tui = { path = "crates/yog-tui" }

anyhow = "1.0.104"
clap = "4.6.7"
crossterm = "0.29.0"
dirs = "7.0.0"
env_logger = "0.11.11"
futures-util = { version = "0.3.34", default-features = false }
gpui-kit = "0.6.6"
indicatif = "0.18.6"
log = "0.4.34"
plotters = { version = "0.3.7", default-features = false }
ratatui = "0.30.2"
rustix = "1.1.5"
serde = "1.0.229"
serde_json = "1.0.151"
sha2 = "0.11.0"
tempfile = "3.27.0"
thiserror = "2.0.21"
tokio = "1.53.1"
tokio-util = "0.7.19"
toml = "1.1.6"
walkdir = "2.5.0"

[profile.release]
opt-level = 3
strip = true
lto = "thin"
panic = "abort"
codegen-units = 1
