[package]
name = "yog-cli"
version.workspace = true
edition.workspace = true

[dependencies]
yog-core = { workspace = true, features = ["clap"] }
tokio = { workspace = true, features = ["rt", "macros", "signal"] }
tokio-util = { workspace = true, features = ["rt"] }
clap = { workspace = true, features = ["derive"] }
rustix = { workspace = true, features = ["fs"] }
indicatif.workspace = true
anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }
toml.workspace = true
dirs.workspace = true
walkdir.workspace = true
env_logger.workspace = true
log.workspace = true

[dev-dependencies]
serde_json.workspace = true

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
panic = "abort"
strip = true

[[bin]]
name = "yog"
path = "src/main.rs"
