[package]
name = "yog-cli"
version.workspace = true
edition.workspace = true

[dependencies]
yog-core = { workspace = true, features = ["clap"] }
yog-runtime.workspace = true

tokio = { workspace = true, features = ["rt", "macros", "signal"] }
tokio-util = { workspace = true, features = ["rt"] }
clap = { workspace = true, features = ["derive"] }
env_logger.workspace = true

[dev-dependencies]
serde_json.workspace = true

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
panic = "abort"
strip = true

[[bin]]
name = "yog"
path = "src/main.rs"
