[package]
name = "yog-gpui"
version.workspace = true
edition.workspace = true

[dependencies]
gpui-kit.workspace = true
log.workspace = true
tokio = { workspace = true, features = ["rt", "sync"] }
tokio-util.workspace = true
yog-core.workspace = true
yog-runtime.workspace = true

[dev-dependencies]
gpui-kit = { workspace = true, features = ["test-support"] }
