[package]
name = "yog-tui"
version.workspace = true
edition.workspace = true

[dependencies]
yog-cli = { workspace = true, optional = true }
yog-core.workspace = true
yog-runtime.workspace = true

crossterm = { workspace = true, features = ["event-stream"] }
futures-util = { workspace = true, features = ["std"] }
ratatui.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
tokio-util = { workspace = true, features = ["rt"] }

[dev-dependencies]
tempfile.workspace = true

[features]
default = ["cli"]
cli = ["yog-cli"]
