[package]
name = "yog-core"
version.workspace = true
edition.workspace = true

[dependencies]
futures-util = { workspace = true, features = ["std"] }
log.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = {
  workspace = true,
  features = [
    "fs",
    "io-util",
    "macros",
    "process",
    "rt",
    "time",
  ]
}
tokio-util = { workspace = true, features = ["io-util", "rt"] }

clap = { workspace = true, features = ["derive"], optional = true }

[features]
clap = ["dep:clap"]
