[package]
name = "yog-runtime"
version.workspace = true
edition.workspace = true

[features]
dev-tools = []

[[example]]
name = "emulate_chart_preview"
required-features = ["dev-tools"]

[dependencies]
anyhow.workspace = true
dirs.workspace = true
indicatif.workspace = true
log.workspace = true
plotters = {
  workspace = true,
  features = [
    "bitmap_backend",
    "bitmap_encoder",
    "line_series",
    "svg_backend",
    "ttf",
  ]
}
rustix = { workspace = true, features = ["fs"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio-util = { workspace = true, features = ["rt"] }
toml.workspace = true
walkdir.workspace = true
yog-core.workspace = true

[dev-dependencies]
clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt"] }
