[package]
name = "yog-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
yog-core.workspace = true
tokio-util = { workspace = true, features = ["rt"] }
rustix = { workspace = true, features = ["fs"] }
indicatif.workspace = true
anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }
toml.workspace = true
dirs.workspace = true
walkdir.workspace = true
log.workspace = true
plotters = { workspace = true, features = [
    "bitmap_backend",
    "bitmap_encoder",
    "line_series",
    "svg_backend",
    "ttf",
] }

[dev-dependencies]
serde_json.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
